### ISSUE TITLE
Rewire the VARS Query to DSCRTP Format.Rmd to source VARS data directly from HURL database

### ISSUE THREAD

**Issue by SarahRDBingo** [DARC-UHM/Data-Processing-Scripts#19]
Currently the R markdown file called "VARS Query to DSCRTP Format.Rmd" relies on an input file "vars_query.txt" to gather data from our database. The query file has to be manually pulled from VARS database using an SQL GUI provided by the developer  and then saved in a specific location each time we review the data after making changes to records. Would be nice if we could bypass the SQL GUI to reduce the number of steps and clicks required to perform QAQC, and eliminate one more possible point of human error introduction. Essentially I would want to see a script  developed in R, Python, or SQL that can operate within the Rstudio GUI to represent the flattened version of a subset of data from VARS database and save it as a dataframe object for performing logical tests.

The VARS field "Video Sequence Name" would be used as the input for selecting which set(s) of records would be pulled from the VARS database into R. Something similar was developed by Seth Royston in his qaqc_and_outputs.py script, but we want to parse out the qaqc portions of this program and repurpose it into the R program.

``

**Comment by fergmastaflex** [comment]
Despite my lack of R knowledge, I might be able to figure this one out. We may need the connection string for the sql db and some credentials/keys if the db is authenticated or encrypted. That can/should be handled off of Github. There's also quite a few articles on connecting to sql dbs via R and looks pretty straightforward.

**Comment by robertgodfrey** [comment]
From what I can tell this is actually solved and we don't need to use SQL at all. There is a public API you can call at http://hurlstor.soest.hawaii.edu:8086/query/dive/[DIVE NAME]

So for the [example text file in the QA/QC folder](https://github.com/DARC-UHM/Data-Processing-Scripts/blob/main/02_QAQC_Annotations/Annotation__Processing/queries/vars_query.txt), you would call http://hurlstor.soest.hawaii.edu:8086/query/dive/Hercules%201341889 (Hercules 1341889 is the video sequence name)

From what I can tell, this returns all the same information as a json object instead of a tsv

**Comment by fergmastaflex** [comment]
@robertgodfrey ah nice callout. Didn't know that. I'll shift to looking into http clients in R and implement the API instead!
